### ISSUE TITLE
Project Release Date

### ISSUE THREAD

**Issue by RFFAITHH** [radkesvat/RTCF#1]
سلام و ارادت مهندس. مهندس این پروژه جدید تاریخ انتشارش مشخص نشد؟ بی صبرانه منتظریم استفاده کنید هم ریورس هم ایپی تیبل دیگه دارن خیلی اذیت میکنن

**Comment by RFFAITHH** [comment]
سلام مهندس وقتتون بخیر من این پیام رو دیدم :         نکته مهم: نیازی نیست منتظر پیاده سازی این پروژه بمونید ؛ تونل معکوس وب سوکت با cdn توسط این [پروژه](https://github.com/jpillora/chisel) ممکن است ؛ ازش استفاده کنید همچنین این [اموزش](https://vegardw.medium.com/reverse-socks-proxy-using-chisel-the-easy-way-48a78df92f29) هم هست کمکتون میکنه

در کل من برای اینکه امکانات مورد نیاز خودم رو بیارم باید این پروژه رو ادامه بدم تا آخر ؛ ولی همونطور که گفتم نیازی نیست شما منتظر باشید


اما بنده دارم از Shadowsocks رو سرورام استفاده مکینم ws ندارم کانفیگ باید منتظر پروژه شما بمونم درسته؟

**Comment by radkesvat** [comment]
نه ربطی نداره به کانفیگ ؛ شدو ساکس رو من استفاده نکردم ولی پیشناهاد میکنم v2ray استفاده کنید

**Comment by RFFAITHH** [comment]
مهندس سلام کمکی بر میاد پروژه سریع تر اوکی شه؟ Chisel باید حتما رو ویندوز هم ران شه طبق چیزی که دیدم واسه فروشنده ها جالب نیست.
