### ISSUE TITLE
Request: Please add dynamic port forwarding too

### ISSUE THREAD

**Issue by OnceUponATimeInAmerica** [radkesvat/RTCF#10]
سلام. با تشکر از زحمات حرفه ای شما در این پروژه و پروژه تونل RTT.

همینطور که میدونید ssh  و همچنین بعضی برنامه های تونل کننده مثل Chisel   از port forwarding بصورت نقطه به نقطه (دیتا در یک زوج آیپی- پورت که یکسر تونل هست،  تحویل گرفته میشه و به یه زوج آبپی-پورت که در کامپیوتر مقصد هست، مثلا xray، تحویل داده میشه) پشتیبانی میکنن.

اما نکته مهم اینه که هر دوی این برنامه ها از dynamic port forwarding  هم پشتیبانی میکنن که دیتا رو در یه سر تونل تحویل میگیره (بصورت یه ساکس پراکسی که برنامه تونل دهنده روش گوش میده) و در سر دیگه تونل، دیتا به  پورت خاصی در کامپیوتر مقصد تحویل نمیشه بلکه به هدف نهایی که در هدر محتویات تونل تعیین شده (مثلا جیمیل پورت 443 یا یاهو پورت 80 یا ....)   فرستاده میشه.   این نحوه کار تا حدی شبیه outbound/protocol freedom در هسته xray  و مشابه اون ها هم هست.

این قابلیت انعطافپذیری تونل رو خیلی بالا میبره و مثلا میشه باهاش پنل v2ray رو روی سرور ایران هم قرار داد (سرور خارجی دیگه غیر از برنامه تونل به چیز دیگه و پنلی احتیاج نداره).

میخواستم بودنم آیا این قابلیت در این پروژه یا پروژه RTT  پیاده سازی شده و یا برنامه ای برای پیاده سازیش دارین؟  چون من در Chisel ازش استفاده کردم و بسیار قابلیت هاش رو افزایش میده. البته میدونم RTT و این پروژه از مولتی پورت هم پشتیبانی میکنن ولی در اینجا منظورم بیشتر dynamic  port forwarding  هست.

 با تشکر.

**Comment by radkesvat** [comment]
سلام متوجه شدم ولی این رو اگه میخواین باید با ابزار های جانبی پیدا کنید ؛ تونلی که از اول هدف از نوشتنش بود روی لایه tcp , udp قراره کار کنه و روی لایه های بالاترش کنترلی نداره
