### ISSUE TITLE
 --add-port:N    قابلیت 

### ISSUE THREAD

**Issue by eylandoo** [radkesvat/RTCF#12]
مهندس سلام  این قابلیت تعریف چنتا پورت خارج از بازه برای اینجا هم مبشه استفاده کرد؟

 --add-port:N

**Comment by radkesvat** [comment]
بله باید کار کنه ولی دقت کنید که سرور خارج به یه سری پورت محدود میتونه کاکنت شه که در سرور ایران باید جزو پورت های لیسن باشن
