### ISSUE TITLE
راهنمایی درباره اجرای تانل روی centos

### ISSUE THREAD

**Issue by Moratagfz** [radkesvat/RTCF#13]
باسلام و خدا قوت خسته نباشید عرض میکنم خدمتتون.
با این پروژه میتوان روی centos تانل رو اجرا کرد؟
من یه سرور خارج centos دارم و یه سرور ایران ubuntu دارم سرور خارجم فیلتره میخوام تانل معکوس اجرا کنم ولی پروژه reverse tls tunnel کار نکرد این روش کارمیکنه یا پیشنهاد دیگه ای دارین؟

**Comment by radkesvat** [comment]
باید build کنید دستی ؛ چرا centos ؟ ابونتو مشکلش چیه؟

**Comment by word1372** [comment]
من هم این روش رو استفاده کردم ایران سنتوس خارج اوبونتو کار کرد ip خارج فیلتر و محدود شده بود فقط نمیدونم این wrn ها وقتی هیچکس وصل نیست چرا میاد 

![Screenshot 2024-01-03 112618](https://github.com/radkesvat/RTCF/assets/13185024/db2d3db7-38e1-4f03-8c7c-c75f574cf51b)

**Comment by Moratagfz** [comment]
> باید build کنید دستی ؛ چرا centos ؟ ابونتو مشکلش چیه؟


> باید build کنید دستی ؛ چرا centos ؟ ابونتو مشکلش چیه؟

راستش به دلیل اپ هایی که دارم (ibsng) نیازه روی centos اجرا کنم.

**Comment by radkesvat** [comment]
> من هم این روش رو استفاده کردم ایران سنتوس خارج اوبونتو کار کرد ip خارج فیلتر و محدود شده بود فقط نمیدونم این wrn ها وقتی هیچکس وصل نیست چرا میاد


این وضعیت داخلیه تونل هست کانکشن باز و بسته بشه لاگ میندازه

**Comment by radkesvat** [comment]
> > باید build کنید دستی ؛ چرا centos ؟ ابونتو مشکلش چیه؟
> 
> > باید build کنید دستی ؛ چرا centos ؟ ابونتو مشکلش چیه؟
> 
> راستش به دلیل اپ هایی که دارم (ibsng) نیازه روی centos اجرا کنم.

قابلیت کامپایل رو قرار خواهم داد ؛ ولی نسخه ای که الان هست رو اگه تونستید تست کنید ببینید ارور دریافت میکنید یا خیر

**Comment by Moratagfz** [comment]
> > > باید build کنید دستی ؛ چرا centos ؟ ابونتو مشکلش چیه؟
> > 
> > 
> > > باید build کنید دستی ؛ چرا centos ؟ ابونتو مشکلش چیه؟
> > 
> > 
> > راستش به دلیل اپ هایی که دارم (ibsng) نیازه روی centos اجرا کنم.
> 
> قابلیت کامپایل رو قرار خواهم داد ؛ ولی نسخه ای که الان هست رو اگه تونستید تست کنید ببینید ارور دریافت میکنید یا خیر

بله
ارور دریافتی:
./RTCF: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./RTCF)

**Comment by radkesvat** [comment]
درسته باید کامپایل بشه ؛‌از بتا در بیاد انجام میدم فعلا میتونید با سرور واسطه ابونتو تانل رو انجام بدین

**Comment by Moratagfz** [comment]
خیلی ممنون مهندس جان خدا قوت
