### ISSUE TITLE
خطا

### ISSUE THREAD

**Issue by hamed141512** [radkesvat/RTCF#16]
داخل سرور ایران خطای زیر رو میده:

ERR could not register the new domain to CloudFlare code=400 details="\"Record already exists.\"" topic=Setup
FAT Registration to CloudFlare was unsuccessful! topic=Setup

در سرور خارج نیز اینو : 

ERR Websocket error                            name=WSFailedUpgradeError msg="Server did not reply with a websocket upgrade: Header code: 521 Header reason:  Address: [2606:4700:3031::ac43:b3bd]:443" topic="Kharej RightSide" thread=2

**Comment by radkesvat** [comment]
سلام سرور ایران ران نشده که این ارور رو میده
