### ISSUE TITLE
تنظیمات کلودفلر

### ISSUE THREAD

**Issue by ZarinNegah** [radkesvat/RTCF#17]
سلام
وقت بخیر
تنظیماتی برای کلودفلر قرارندادین
کاری نیاز نیست ما بکنیم
الان ارتباط سرور ایران با خارج به آی پی ها کلودفلر هستش؟
دیگه فیلتر بودن آی پی خارجمون اهمیتی نداره؟
همچنین گزینه پروکسی کلوفلر و جایی نیاز نیست ما فعال کنیم؟
تشکر

**Comment by radkesvat** [comment]
سلام برای حالت اتومات هیچ کار خاصی نیاز نیست برای حالت دامنه شخصی اموزش قرار داده شد
