### ISSUE TITLE
arm

### ISSUE THREAD

**Issue by ZarinNegah** [radkesvat/RTCF#18]
سلام
وقت بخیر
مهندس لطفا نسخه های مرتبط با سی پی یو arm هم قرار دهید در کنار amd
تشکر

**Comment by radkesvat** [comment]
چشم از بتا دربیاد حتما قرار میدم، اپل مطمعن شم درست کار میکنه

**Comment by ZarinNegah** [comment]
> چشم از بتا دربیاد حتما قرار میدم، اپل مطمعن شم درست کار میکنه

سلام
تشکر

**Comment by ZarinNegah** [comment]
سلام
وقت بخیر
مهندس این نسخه 0.7 بنظر بهتر شده
امکانش هست برای این نسخه و به بعدش arm هم اضافه کنید به فایل ها
لطفا
