### ISSUE TITLE
جابجا بودن لینک نسخه Multi Thread و Single Thread

### ISSUE THREAD

**Issue by MAMSEIN** [radkesvat/RTCF#19]
با سلام و خسته نباشید.
ابتدا عرض کنم که لینک های دو نسخه را جابجا قرار دادید لطفا این رو درست کنید.
درضمن بنده هرکاری کردم نتونستم تونل رو برقرار کنم چه با Auto mode روشن و خاموش. هم دستی دامنه و سرتیفیکت زدم نشد اتوماتیک هم نشد.
البته ظاهرا هر مشکلی هست از سمت سرور خارجه چون داخل سرور ایران ارور نمیگیرم.
و یک موضوع دیگه که من فقط دیدم از پروتکل TCP استفاده میشه برای این تونل درسته؟ یعنی وایرگارد نمیتونیم روش تست کنیم؟

دستوری که داخل سرور ایران میزنم:
./RTCF --iran --auto:off --cert:/root/cert.cert --pkey:/root/key.key --domain:host.xxx.com --lport:23-65535 --password:021

و دستوری که سرور خارج میزنم. با دو سرور دیگه هم تست کردم:
./RTCF --kharej --auto:off --domain:host.xxx.com --iran-port:443 --toip:127.0.0.1 --toport:8443 --password:021

پورت های مختلف Cloudflare رو هم تست کردم اما بازم جواب نداد.

اسکرین شات از سرور ایران:
![image](https://github.com/radkesvat/RTCF/assets/13032540/527488d5-702d-449f-9aa2-3573ab819275)

اسکرین شات از سرور خارج:
![image](https://github.com/radkesvat/RTCF/assets/13032540/088e69da-b2af-4394-a5c8-d2990def70bd)

لطفا این رو توضیح دهید که در سرور خارج قسمت وارد کردن دامنه همون دامنه ای که تو Cloudflare حالت پروکسی روشن ثبت کردیم رو باید وارد کنیم درسته؟ همون آدرسی که برای سرور داخل وارد کردم.
ممنون میشم راهنمایی کنید. همچنین امکان Noise رو هم برای آپلود فیک اگر اوکی نشده قرار دهید.

باتشکر

**Comment by danyalfa79** [comment]
سلام. من هم دقیقا مشکل مشابه و همین ارور رو دارم

چند روز قبل با نسخه 0.1 امتحان کرده بودم این مشکل وجود نداشت

**Comment by radkesvat** [comment]
سلام بله ؛ فیکس شد الانم یه اپدیت میاد

**Comment by danyalfa79** [comment]
> سلام بله ؛ فیکس شد الانم یه اپدیت میاد

درود مهندس
اسکریپت هنوز نسخه 0.3 رو اینستال میکنه

**Comment by MAMSEIN** [comment]
> سلام بله ؛ فیکس شد الانم یه اپدیت میاد

سلام و درود
ممنون از شما، اما متاسفانه همچنان مشکل پا برجاست و همون ارور های بالا رو میگیرم.

**Comment by ZarinNegah** [comment]
> > سلام بله ؛ فیکس شد الانم یه اپدیت میاد
> 
> سلام و درود ممنون از شما، اما متاسفانه همچنان مشکل پا برجاست و همون ارور های بالا رو میگیرم.

ادیت نکردن ورژن روی فال نصب
همچنان داره نسخه 0.3 نصب میشه و 0.4 نیست در فایلشون برای نصب

**Comment by danyalfa79** [comment]
من کماکان حتی بعد از آپدیت 0.5 هم همین مشکل رو دارم
پورت رو هم تغییر دادم ولی تفاوتی نکرده

**Comment by radkesvat** [comment]
دقیقا همین مشکلو ‌دارید که عکسشو فرستادید؟ لاگ ها یکسانن؟

**Comment by radkesvat** [comment]
فعلا فقط تی سی پی تست ، از باا در بیاد یو دی پی هم فعال میشه

**Comment by radkesvat** [comment]
دامنه ای که وارد میکنید باید پروکسی روشن باشه و ایپی سرور ایران داخلش باشه

**Comment by radkesvat** [comment]
لطفا اگه با نسخه پنج مشکل دارید و مشکلتون خل نشده یه بار دیگه به همین شکل عکس از لاگ قرار بدین

**Comment by danyalfa79** [comment]
![Screenshot 2024-01-04 205301](https://github.com/radkesvat/RTCF/assets/126307500/99399d13-7b6d-4596-af6d-b200d6d9fdf5)

**Comment by radkesvat** [comment]
دامنه ای که استفاده میکنید تازه وارد کلود فلیر کردین یا از قبل تر داشتین ؟

**Comment by ZarinNegah** [comment]
> دامنه ای که استفاده میکنید تازه وارد کلود فلیر کردین یا از قبل تر داشتین ؟
> 
> تنظیمات خاصی روش ست کردین؟
> 
> با حالت auto همین مشکل رو دارید؟

سلام
مهندس حتما باید دامنه خودم داشته باشیم
یا حالت اتوماتیک شما هم ممکنه با سرور اکی باشه و مشکلی نداشته باشیم؟

**Comment by radkesvat** [comment]
میتونه اکی باشه محض احتیاط گفتم که دامنه شخصی امن تره در کل

**Comment by ZarinNegah** [comment]
> میتونه اکی باشه محض احتیاط گفتم که دامنه شخصی امن تره در کل

ممنون
آخه دامنه ir یکم ریسکیه

**Comment by danyalfa79** [comment]
> دامنه ای که استفاده میکنید تازه وارد کلود فلیر کردین یا از قبل تر داشتین ؟
> 
> تنظیمات خاصی روش ست کردین؟
> 
> با حالت auto همین مشکل رو دارید؟

تقریبا یکسال هست این دامنه رو روی کلودفلر دارم
بدون پروکسی سرتیفیکیت گرفتم و بعد پروکسی رو روشن کردم
با حالت auto هم  در ورژن 0.6 این مشکل پابرجاست
این مشکل در ورژن 0.1 وجود نداشت و برای چند دقیقه تستش کردم
