### ISSUE TITLE
Auto install script

### ISSUE THREAD

**Issue by The-Erf** [radkesvat/RTCF#2]
سلام اگر دوست دارید اسکریپت نصب خودکارش رو بسپارید به من❤️

**Comment by radkesvat** [comment]
سلام ؛ هنوز اینترفیس ستاپ کردنش کامل نشده برای همین مطمعن نیستم بشه اینکارو کرد ؛ اولین نسخه اش که کامل بشه میتونید یه نصب کننده براش درست کنید ؛ ممنون از لطفتون ♥
