### ISSUE TITLE
فیلتر شدن دامنه

### ISSUE THREAD

**Issue by DontJer** [radkesvat/RTCF#20]
درود خسته نباشید.
حدود ۳ روزی هست که کانفیگ‌هایی که از کلادفلر (ws+tls) استفاده میکنن هر صبح دامنه‌ای که به عنوان اس‌ان‌ای استفاده شده به طور کامل بسته میشه (موقعی که از دامنه پینگ گرفته میشه 10.10.34.35 برمیگردونه)
خواستم بدونم استفاده از این تانل همچین مشکلی رو بوجود نمیاره ؟

**Comment by radkesvat** [comment]
خیر این روش معکوس هستش
