### ISSUE TITLE
تانل دو سرور خارج

### ISSUE THREAD

**Issue by sajadshadmn** [radkesvat/RTCF#21]
درود استاد
به نظر شما اگر دو تا سرور خارج رو با ریورس به هم تانل کنیم
سرور خارج اول که جای ایران کانفیگ میکنیم با توجه به اینکه در خواست از سرور خارج دوم شروع میشه چقدر میتونه از فیلتر شدن سرور خارج اول کمک کنه؟
با فرض بر اینکه کانفیگها رو هم وب سوکت بزنیم
با توجه به اینکه در این حالت چک ایپی فقط ایپی سرور خارج دوم رو نشان میده نه سرور خارج اول که دایرکت بهش وصلیم
ممنون

**Comment by radkesvat** [comment]
هیچ تاثیری در کانفیگ های مستقیم نداره ؛ اتصال تونل ها باید از فایروال عبور کنه وگر نه اتقاف خاصی نمیفته و فایروال تغییری نمیبینه
