### ISSUE TITLE
پنل نصب شده در ایران

### ISSUE THREAD

**Issue by kalilovers** [radkesvat/RTCF#23]
سلام وقت بخیر من بخاطر استفاده از ایپی لیمیت و یه سری موردای دیگه مجبورم پنل رو روی ایران نصب کنم و از این نظر نمیتونم از این تانل جدید استفاده کنم ، آیا روشی هستش که بتونم از این تانل rtcf استفاده کنم درحالی که کاربرا رو ایران باشن؟

**Comment by radkesvat** [comment]
میشه توی تنظیمات xray پنل با اوت بوند از تونل دیتا رو رد میکنید

**Comment by MoeinNS** [comment]
> میشه توی تنظیمات xray پنل با اوت بوند از تونل دیتا رو رد میکنید

منو راهنمایی میکنی ببینم مشکلم  
https://github.com/radkesvat/RTCF/issues/22

**Comment by kalilovers** [comment]
> میشه توی تنظیمات xray پنل با اوت بوند از تونل دیتا رو رد میکنید

وقت بخیر ، در این صورت تانل شما چطور کار میکنه ؟ چون تانل اوتباند به روش خودش انتقال میده ترافیک رو
