### ISSUE TITLE
خطا در سرور خارج

### ISSUE THREAD

**Issue by ZarinNegah** [radkesvat/RTCF#24]
سلام
وقت بخیر
مهندس جان نسخه نصب کردم
ولی این خطا در سرور خارج دریافت میکنم و ارتباط برقرار نمیشه کلا بین دو سرور 

![image](https://github.com/radkesvat/RTCF/assets/39865873/ae8ff583-a0a5-4b03-a349-502c360a01dd)

**Comment by radkesvat** [comment]
پورت کانفیگ رو اشتباه زدین در دستور سرور خارج

> --toport

**Comment by ZarinNegah** [comment]
> پورت کانفیگ رو اشتباه زدین در دستور سرور خارج
> 
> > --toport
حالت مالتی هست
--toport:multiport

**Comment by MoeinNS** [comment]
دقیقا منم همین مشکل رو دارم

**Comment by alila23** [comment]
این موارد رو در cloudflare چک کنید همچنین تیک ws
![1](https://github.com/radkesvat/RTCF/assets/140375365/42e3cd48-e706-4118-98fe-f52df553d913)
![2](https://github.com/radkesvat/RTCF/assets/140375365/ee8da868-bd1d-40cf-b83b-2dc771f7b9a7)

**Comment by ZarinNegah** [comment]
سلام
این خطا در نسخه 0.7 دیده نشد و به درستی سرور متصل شد ( در 0.6 نمیشد )

**Comment by ZarinNegah** [comment]
سلام
مهندس
لطفا نسخه arm هم زودتر قراردهید
بتونیم تست کنیم
اکثرا سرورهامون از اون سی پی یو پشتیبانی میکنه هتزنر
تشکر فراوان
