### ISSUE TITLE
مشکل در اتصال دو سرور

### ISSUE THREAD

**Issue by mrcodebaz** [radkesvat/RTCF#25]
سلام ، تشکر از زحماتتون

من با حالت اتوماتیک متصل کردم و شد

بعد دامنه شخصی خودم رو زدم و هرکاری کردم نشد 

این تصویر سرور خارجه که مدام میخواد متصل بشه و نمیشه :
![image](https://github.com/radkesvat/RTCF/assets/155746341/799a5fd8-413f-4f44-9b53-49e766315d09)

اینم تصویر سرور ایرانه که ظاهرا درست متصل شده و منتظر اتصال سرور خارجه : 
![image](https://github.com/radkesvat/RTCF/assets/155746341/3d42e27f-a32b-4954-8aba-abadd9e5c557)

دستوراتی که دامنه شخصیمو زدم :
```
./RTCF --auto:off --iran --cert:/root/cert.cert --pkey:/root/key.key --domain:CDNSUB  --lport:22-65535 --password:123

./RTCF --kharej --auto:off --domain:CDNSUB --iran-ip:MYIP --iran-port:443 --toip:127.0.0.1 --toport:multiport --password:123
```

ممنون میشم راهنمایی کنید

**Comment by danyalfa79** [comment]
مشکل مشابه رو دارم. کامنت آخر این ایشو که کلوز شد:
https://github.com/radkesvat/RTCF/issues/19

**Comment by mrcodebaz** [comment]
> مشکل مشابه رو دارم. کامنت آخر این ایشو که کلوز شد: #19

نسخه 0.7 هم امروز ارائه دادن، ولی باز هم اوکی نشده
معلوم نیست چه کاری رو واسه دامنه شخصیمون انجام ندادیم !
ببینیم سازنده چه جوابی بهمون میدن

**Comment by Asfia7** [comment]
منم این مشکلو دارم

**Comment by alila23** [comment]
برا دامنه شخصی این دو مورد رو چک کنید ssl رو هم چک کنید
![1](https://github.com/radkesvat/RTCF/assets/140375365/88c0e8d3-42ec-4f31-bc4f-9145bc47a4f6)
![2](https://github.com/radkesvat/RTCF/assets/140375365/03b93a60-846e-40d9-bb7d-eed68397e75e)

**Comment by radkesvat** [comment]
تنظیمات کلود فلیر minimum ssl رو بزارید روی 1.1

**Comment by mrcodebaz** [comment]
مچکرم حل شد
