### ISSUE TITLE
کرش با دامنه شخصی سمت سرور ایران روی ورژن 0.7

### ISSUE THREAD

**Issue by diditra** [radkesvat/RTCF#26]
درود و خسته نباشید.
من با auto:on متصل میشم و مشکلی نداره ولی وقتی این کامند رو با دامنه شخصی روی سرور ایران ران میکنم نرم افزار درجا کرش میکنه. (دامنه اصلی و رمز رو مخفی کردم)
/root/RTCF --iran --auto:off --cert:/root/cert.cert --pkey:/root/key.key  --domain:something.xxx.site --lport:23-65535 --password:pass

خروجی:

```
INF Application Version                        version=0.7 topic=Setup
INF Application Mode                           mode=iran topic=Setup
fs.file-max = 1000000
INF Resolved                                   selfip=188.121.98.147 topic=Setup
INF Resolved                                   domain=something.xxx.site points at:=172.67.147.5 topic=Setup
NOT Initialized                                topic=Setup
Firewall stopped and disabled on system startup
INF reseting iptable nat                       topic=Iran
INF Finding internal port                      topic=Iran
INF Started tcp server                         listen=:: port=25500 topic="Iran LeftSide" thread=1
asyncfutures.nim(674)    cb
Error: unhandled exception: Asynchronous task [run() at right.nim:105] finished with an exception "TLSStreamProtocolError"!
Message: Invalid PEM encoding
Stack trace: tlsstream.nim(143)       raiseTLSStreamProtocolError
right.nim(112)           run
dynamic_scope.nim(90)    run
 [FutureDefect]
```

**Comment by alila23** [comment]
فایل ssl که برای دامنه شخصیت گرفتی مشکل داره احتمالا فایل تکست توی ویندوز ساختی انتقال دادی , داخل کلود فلر هم به این صورت عمل کن من استفاده کردم بسیار پایدار و پرسرعته فقط اگر سرور ایران رو به عنوان نود سرور خارج متصل کرده باشی اتصال داکر رو قطع میکنه بخاطر رول های iptable
![1](https://github.com/radkesvat/RTCF/assets/140375365/a5076eac-f9a3-495c-a925-e933f0f02b90)
![2](https://github.com/radkesvat/RTCF/assets/140375365/c4816555-e87b-4933-a468-0be9f9fa4376)

**Comment by radkesvat** [comment]
درسته به نظرم سرتیفکیت رو درست وارد نکردید ؛‌ در ویندوز فایلش رو نسازید

**Comment by diditra** [comment]
مشکل از اینجا بود که سرتیفیکت رو وقتی از cloudflare کپی میکردم یه new line تهش داشت. اون رو پاک کردم درست شد.

**Comment by engAmirEng** [comment]
برای من مشکلش این بود که وقتی با vim کپی میکردم مشکل داشت ولی وقتی با nano کپی میکنم درسته😀
