### ISSUE TITLE
گزارش مشکل با تست اسپید 

### ISSUE THREAD

**Issue by mrcodebaz** [radkesvat/RTCF#29]
سلام
دیشب تست اسپید گرفتم و سرور رو کلا قطع کرد
تانل chisel هم این مشکل رو داشت
و ظاهراً هم فقط شبا این مشکلو پیش میاره!

گفتم بهتون گزارش بدم مد نظرتون باشه
شاید سایت‌های دیگه هم چنین مشکلی پیش بیارن!!

من فعلا برای جلوگیری از قطعی دسترسی کاربرا به تست اسپید رو بستم.

**Comment by radkesvat** [comment]
تو نسخه جدید باید فیکس شده باشه؛ به نظرم همیشه با اسیپد تست چک کنید چون اسپید تست خودش علت نیست ؛ اسپید تست فقط نماد یه دانلود شدیده
