### ISSUE TITLE
متصل نشدن با دامین شخصی

### ISSUE THREAD

**Issue by nimaviper031** [radkesvat/RTCF#31]
سلام
وقتی که auto:off استفاده می کنم و domain بهش میدم متصل نمیشه اما با auto:on وصل میشه مشکلی نداره.
![kharej](https://github.com/radkesvat/RTCF/assets/155872526/89cba84f-38b5-4564-8ec5-f984c77d7c93)
![IRAN](https://github.com/radkesvat/RTCF/assets/155872526/96cc9116-3c54-45c0-9faf-6d16e77154be)

**Comment by radkesvat** [comment]
تنیظمات کلود فلیر رو چک کنید  
minimum tls versios رو بزارید 1.1

**Comment by nimaviper031** [comment]
> تنیظمات کلود فلیر رو چک کنید minimum tls versios رو بزارید 1.1

گذاشتمش روی همین اما بازم وصل نمیشه.
کلودفلیر چه تنظیماتی باید داشته باشه؟

**Comment by mepjnik** [comment]
دامین ای که برای RTCF استفاده میکنید باید جدا از دامین ای باشه که برای کانفینگهای پنل x-ui استفاده میشه . من مشکل اتصال داشتم می خواستم از همون دامین با اختصاص ی دامین دیگه ارتباط به راحتی برقرار شد.

**Comment by nimaviper031** [comment]
> دامین ای که برای RTCF استفاده میکنید باید جدا از دامین ای باشه که برای کانفینگهای پنل x-ui استفاده میشه . من مشکل اتصال داشتم می خواستم از همون دامین اتصال رو برقرار کنم همین خطای شما رو داشتم . با اختصاص ی دامین دیگه ارتباط به راحتی برقرار شد.

سلام
مرسی ممنون اوکی از یه دامین جدا استفاده میکنم.

**Comment by nimaviper031** [comment]
> دامین ای که برای RTCF استفاده میکنید باید جدا از دامین ای باشه که برای کانفینگهای پنل x-ui استفاده میشه . من مشکل اتصال داشتم می خواستم از همون دامین اتصال رو برقرار کنم همین خطای شما رو داشتم . با اختصاص ی دامین دیگه ارتباط به راحتی برقرار شد.

این هم جواب نداد.

**Comment by nimaviper031** [comment]
مشکلم حل شد.
تنظیمات SSL/TLS encryption mode روی Full نبود گذاشتمش روی Full اوکی شد.
و باقی تنظیمات را طبق این کامنت انجام دادم و اوکی شد.
[https://github.com/radkesvat/RTCF/issues/27#issuecomment-1879584813](url)

**Comment by nimaviper031** [comment]
مشکلم حل شد.
تنظیمات SSL/TLS encryption mode روی Full نبود گذاشتمش روی Full اوکی شد.
و باقی تنظیمات را طبق این کامنت انجام دادم و اوکی شد.
[https://github.com/radkesvat/RTCF/issues/27#issuecomment-1879584813](https://github.com/radkesvat/RTCF/issues/27#issuecomment-1879584813)
