### ISSUE TITLE
آیا مشکل فریز شدن رلیز های اینستاگرام حل شده؟

### ISSUE THREAD

**Issue by m2tts2001** [radkesvat/RTCF#33]
درود دوستان گرامی
کسانی که از این روش استفاده کردند ممنون میشم جواب بدند که مشکل فریز شدن و قطعی مقطعی ریلز های اینستاگرام براشون حل شده یا نه
چون در پروژه RTT مشکلی که داشتیم این بود که مثلا بعد از ٢٠ تا ویدیو یهو قفل میکرد و ریلز پخش نمیشد. 
آیا این پروژه این مشکل رو حل کرده؟
یه خسته نباشید هم بگم به سازنده و تمام افرادی که در پروژه سهیم هستند. دست خوش

**Comment by merry682** [comment]
سلام
چند روزی دارم استفاده میکنم مشکلی در مورد اینستاگرام ندیدم

> درود دوستان گرامی کسانی که از این روش استفاده کردند ممنون میشم جواب بدند که مشکل فریز شدن و قطعی مقطعی ریلز های اینستاگرام براشون حل شده یا نه چون در پروژه RTT مشکلی که داشتیم این بود که مثلا بعد از ٢٠ تا ویدیو یهو قفل میکرد و ریلز پخش نمیشد. آیا این پروژه این مشکل رو حل کرده؟ یه خسته نباشید هم بگم به سازنده و تمام افرادی که در پروژه سهیم هستند. دست خوش

**Comment by Ferixy** [comment]
> درود دوستان گرامی
> کسانی که از این روش استفاده کردند ممنون میشم جواب بدند که مشکل فریز شدن و قطعی مقطعی ریلز های اینستاگرام براشون حل شده یا نه
> چون در پروژه RTT مشکلی که داشتیم این بود که مثلا بعد از ٢٠ تا ویدیو یهو قفل میکرد و ریلز پخش نمیشد. 
> آیا این پروژه این مشکل رو حل کرده؟
> یه خسته نباشید هم بگم به سازنده و تمام افرادی که در پروژه سهیم هستند. دست خوش

سلام بله خیلی بهتر شده. میتونید استفاده کنید.
