### ISSUE TITLE
عدم برقراری تانل

### ISSUE THREAD

**Issue by sajadshadmn** [radkesvat/RTCF#35]
درود بر شما مهندس
ممنونیم از وقت و تلاش شما
چندین بار اقدام به تانل کردم موفق نشدم 
قطعا یه جای کار اشتباه میکنم
اگر منت بگذارید و اسکریپت نصب لطف بفرمایید بینهایت ممنونتون میشم
زنده باشید

**Comment by Ferixy** [comment]
> درود بر شما مهندس
> ممنونیم از وقت و تلاش شما
> چندین بار اقدام به تانل کردم موفق نشدم 
> قطعا یه جای کار اشتباه میکنم
> اگر منت بگذارید و اسکریپت نصب لطف بفرمایید بینهایت ممنونتون میشم
> زنده باشید

سلام بجای اینکه منتظر اسکریپت نصب باشید میتونید جزئیات بیشتری از مشکلتون بدید که درصورت امکان حل بشه.
