### ISSUE TITLE
چطور میشه از امکان آپلود فیک توی پروژه های دیگه استفاده کرد؟

### ISSUE THREAD

**Issue by MAMSEIN** [radkesvat/RTCF#4]
با سلام وقت بخیر
متاسفانه مشکلی که هست اینه که نمیشه از قابلیت آپلود فیک توی پروژه های دیگه استفاده کرد مثل Chisel و UDP2RAW و غیره. من از این پروژه ها استفاده کردم و هنوز هم میکنم. خیلی هم پرسرعت و خوب هستن تنها مشکل همین امکان آپلود فیک هست. میشه بفرمایید چطوری میتونیم اون بخش از پروژه RTT شما رو که شامل آپلود فیک هست روی این سرویس ها برقرار کنیم؟ اصلا امکانش هست؟
ممنون

**Comment by radkesvat** [comment]
والا اسکریپت نامیزون هست خودش حساب میکنه ولی udp اپلود میکنه دیتا سنتر ها میتونن بفهمن (و شنیدم دیتا سنتر های حساس هستن روش و به راحتی میفهمن )

**Comment by radkesvat** [comment]
تونل من اپلود فیک رو انجام میده چون دیتا از خودش رد میشه و آمارشو داره و کانکشن هم دست خودشه ؛ برای همین به نظرم امکانش نیست 
که فقط اپلود فیک رو انجام بده برای بغیه تونل ها؛ در کل من این پروژه رو ول نکردم تمومش میکنم و امکاناتی که تا جایی که میدونم چیزل نداره  نظیر مالتی پورت ؛ انتقال udp روی tcp و اپلود فیک و 0rtt رو بهش اضافه میکنم

**Comment by MAMSEIN** [comment]
بله. منم از نامیزون استفاده میکنم. اما به درد مصرف های کم میخوره. به محض اینکه یه مقدار مصرف دیتا بالا بره در شبانه روز هشدار میاد از دیتاسنتر. البته بیشتر توی هاست ایران این هشدار رو دیدم.

**Comment by MAMSEIN** [comment]
> تونل من اپلود فیک رو انجام میده چون دیتا از خودش رد میشه و آمارشو داره و کانکشن هم دست خودشه ؛ برای همین به نظرم امکانش نیست که فقط اپلود فیک رو انجام بده برای بغیه تونل ها؛ در کل من این پروژه رو ول نکردم تمومش میکنم و امکاناتی که تا جایی که میدونم چیزل نداره نظیر مالتی پورت ؛ انتقال udp روی tcp و اپلود فیک و 0rtt رو بهش اضافه میکنم

دم شما گرم. لطف میکنید.
یه امکان خیلی خوبی که UDP2RAW داره اینه که پینگ خیلی پایینی میشه گرفت. حتی از داخل سرور وقتی به سرور خارج پینگ میگیرم هرچی که باشه زمانی که تونل میکنم با UDP2RAW این پینگ وقتی با سیستم خودم با VPN کانکت میشم بهش 10 تا پایینتر از سرور هست. این برای بازی عالیه!
اگر وقت کردید به پروژه UDP2RAW هم یه سری بزنید ببینید چجوریه. من با Wireguard و OpenVPN از این پروژه استفاده میکنم. محشره.
