### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Asfia7** [radkesvat/RTCF#40]
سلام مهندس وقتتون بخیر

من تانل رو تست کردم. سرعتش واقعا بینظیره مخصوصا اگه با ایپی تمیز کلودفلر تست بشه روی حالت auto:off

ولی یه مشکی که هست بعد از تقریبا 1 ساعت روی سرور ایران این خطا میاد و تانل قطع میشه 

Segmentation fault (core dumped)
مشکل از چیه؟

**Comment by s43c** [comment]
> سلام مهندس وقتتون بخیر
> 
> من تانل رو تست کردم. سرعتش واقعا بینظیره مخصوصا اگه با ایپی تمیز کلودفلر تست بشه روی حالت auto:off
> 
> ولی یه مشکی که هست بعد از تقریبا 1 ساعت روی سرور ایران این خطا میاد و تانل قطع میشه
> 
> Segmentation fault (core dumped) مشکل از چیه؟

از سوییچ cdn استفاده نکن بزار خودش آی پی پیدا کنه

**Comment by radkesvat** [comment]
نسخه رو چک کنید ؛‌این ارور در نسخه ۱ باید رفع شده باشه

**Comment by Eslender73** [comment]
عاشق کارتونم❤️❤️❤️

**Comment by Asfia7** [comment]
> نسخه رو چک کنید ؛‌این ارور در نسخه ۱ باید رفع شده باشه

اره رفع شده
کارتون درسته❤️🔥
