### ISSUE TITLE
مشکل در نصب در سرور ایران

### ISSUE THREAD

**Issue by ali90500** [radkesvat/RTCF#43]
سلام وقت به خیر
خسته نباشید 
ببخشید هنگام نصب در سرور ایران با ارور زیر مواجه میشم

install_mt.sh: line 95: unzip: command not found
chmod: cannot access 'RTCF': No such file or directory
finished.

**Comment by ZarinNegah** [comment]
apt install unzip -y

**Comment by ali90500** [comment]
تشکر

**Comment by ali90500** [comment]
سرور ایران مشکل داشت اوکی شد
