### ISSUE TITLE
مولتی پورت

### ISSUE THREAD

**Issue by NIKA5050** [radkesvat/RTCF#46]
با سلام خسته نباشی خدمت دوست عزیز .... لطفا قابلیت مولتی پورت فعال میکنید چون واقعا برای ما که کلاینت با پورت متنوع داریم روی v2 سخته تک تک بخوایم تعریف کنیم پورت را....گزینه مولتی پورت فعال بشه عالیه با تشکر

**Comment by radkesvat** [comment]
فعال هست گیت را بخونید توضیحش هست
