### ISSUE TITLE
سرور واسط

### ISSUE THREAD

**Issue by majiix** [radkesvat/RTCF#5]
سلام مهندس خسته نباشی. میخواستم بدونم این روش نیاز ما رو به سرور واسط که در واقع سرور ایران هست بی نیاز میکنه؟ من الان سرورهام روی والتر هست، همه چی عالیه اما اگه مستقیم آی پی رو بزارم روی دامین و تونل نزنم هر 8 ساعت تقریبن میشه گفت که آی پی فیلتر میشه روی بعضی اپراتورها، به خصوص موبایل. این روش  میتونه چنین مشکلی رو حل کنه بدون سرور ایران؟

**Comment by ZarinNegah** [comment]
سلام
خیر
این هم یک روش تانل خارج به ایران هست
با تفاوت اینکه آی پی سرور خارج از سرور ایران مخفی نگه میداره در صورت استفاده از پروکسی کلودفلر
