### ISSUE TITLE
  single thread حداکثر تعدادکاربران در 

### ISSUE THREAD

**Issue by MahdiMadhani** [radkesvat/RTCF#55]
سلام و خدا قوت
مهندس حداکثر , چه تعداد کاربران را  میتوانیم  در single thread استفاده کنیم  ؟

**Comment by Ferixy** [comment]
>  سلام و خدا قوت
> مهندس حداکثر , چه تعداد کاربران را  میتوانیم  در single thread استفاده کنیم  ؟

سلام سیپیوی سرور چیه؟ dedicated هست؟

**Comment by radkesvat** [comment]
بستگی به cpu سرور داره ولی خوب میانگین حدود ۸۰ تا ۱۰۰

**Comment by MahdiMadhani** [comment]
> بستگی به cpu سرور داره ولی خوب میانگین حدود ۸۰ تا ۱۰۰

سپاس مهندس

**Comment by MahdiMadhani** [comment]
> سلام و خدا قوت مهندس حداکثر , چه تعداد کاربران را میتوانیم در single thread استفاده کنیم ؟

CPU: 1 Core
Speed: 3.79 GHz
