### ISSUE TITLE
arm64 نسخه

### ISSUE THREAD

**Issue by ahmad-79** [radkesvat/RTCF#56]
سلام مهندس

آقا ما چند ماهه مشتری ثابت RTT با ipv6 هستیم و خیلی بهتره نسبت به بقیه روش‌های تانل
دست مریزاد واقعا

فقط خواستم این تانل جدیدو تست کنم چون سرور خارجم arm هستش نشد
فعلا هم اکانت هتزنر ندارم سرور بگیرم خودم خودم بیلد کنم
ممنون میشم نسخه arm رو هم بذارید ی مقایسه بکنیم تانل ها رو

ممنون

**Comment by radkesvat** [comment]
سلام از اپدیت بعد قرار میدم حتما
