### ISSUE TITLE
عدم اتصال

### ISSUE THREAD

**Issue by mohamad15516** [radkesvat/RTCF#59]
با سلام خیلی تلاش کردم ایشیو باز نکنم ولی نمیشد دوستان من کد رو توی سرور داخل به این شکل اجرا کردم 
```
./RTCF --iran --auto:off --cert:/etc/letsencrypt/live/sub.exampel.com/fullchain.pem --pkey:/etc/letsencrypt/live/sub.exampel.com/privkey.pem --domain:sub.exampel.com --iran --lport:443-8443 --password:1234
```
و ارور زیر رو گرفتم 
![Screenshot_20240110_145755_Termius.jpg](https://github.com/radkesvat/RTCF/assets/113285931/936d8507-7d66-459e-b6d8-6d6f996570cb)

و کد زیر رو هم توی سرور خارج اجرا کردم همزمان
```
  ./RTCF --kharej --auto:off --domain:sub.exampel.com --iran-port:443 --toip:127.0.0.1 --toport:443 --password:1234
```
که به ارور زیر برخورد کردم تنظیمات کلودفلر روی تنظیماتی بود که دوستان پیشنهاد کرده بودند و ایپی ایران هم پشت کلود بود 
![Screenshot_20240110_150213_Termius.jpg](https://github.com/radkesvat/RTCF/assets/113285931/b5d008f2-5134-412e-8048-051fc0bc0467)

حالا ممنون میشم بفرمایید کجای کارو اشتباه رفتم 😁😅

**Comment by Eslender73** [comment]
بنظرم از سرتیفیتیکیت کلادفلر استفاده کن بعد تست کن طبق اموزش

**Comment by mohamad15516** [comment]
> بنظرم از سرتیفیتیکیت کلادفلر استفاده کن بعد تست کن طبق اموزش

بله خیلی دوست دارم از کلود استفاده کنم ولی چون دسترسی به سیستم ندارم و با گوشی هستم بعد از کپی و توی nano سرتیفیکیت ها درهم و برهم میشند مجبور شدم از این روش استفاده کنم

**Comment by Eslender73** [comment]
> > بنظرم از سرتیفیتیکیت کلادفلر استفاده کن بعد تست کن طبق اموزش
> 
> بله خیلی دوست دارم از کلود استفاده کنم ولی چون دسترسی به سیستم ندارم و با گوشی هستم بعد از کپی و توی nano سرتیفیکیت ها درهم و برهم میشند مجبور شدم از این روش استفاده کنم

منم با گوشی درست کردم فکر نکنم مشکلی پیش بیاره یبار دیگه امتحان کن

**Comment by mohamad15516** [comment]
> > > بنظرم از سرتیفیتیکیت کلادفلر استفاده کن بعد تست کن طبق اموزش
> > 
> > بله خیلی دوست دارم از کلود استفاده کنم ولی چون دسترسی به سیستم ندارم و با گوشی هستم بعد از کپی و توی nano سرتیفیکیت ها درهم و برهم میشند مجبور شدم از این روش استفاده کنم
> 
> منم با گوشی درست کردم فکر نکنم مشکلی پیش بیاره یبار دیگه امتحان کن

نه چپکی میشه با چه برنامه ای shh زدی ؟

**Comment by Eslender73** [comment]
با برنامه termiuse 

> > > > بنظرم از سرتیفیتیکیت کلادفلر استفاده کن بعد تست کن طبق اموزش
> > > 
> > > 
> > > بله خیلی دوست دارم از کلود استفاده کنم ولی چون دسترسی به سیستم ندارم و با گوشی هستم بعد از کپی و توی nano سرتیفیکیت ها درهم و برهم میشند مجبور شدم از این روش استفاده کنم
> > 
> > 
> > منم با گوشی درست کردم فکر نکنم مشکلی پیش بیاره یبار دیگه امتحان کن
> 
> نه چپکی میشه با چه برنامه ای shh زدی ؟

برنامه termius

**Comment by mohamad15516** [comment]
> > > بنظرم از سرتیفیتیکیت کلادفلر استفاده کن بعد تست کن طبق اموزش
> > 
> > بله خیلی دوست دارم از کلود استفاده کنم ولی چون دسترسی به سیستم ندارم و با گوشی هستم بعد از کپی و توی nano سرتیفیکیت ها درهم و برهم میشند مجبور شدم از این روش استفاده کنم
> 
> منم با گوشی درست کردم فکر نکنم مشکلی پیش بیاره یبار دیگه امتحان کن

و دستوراتی که زدی رو هم میدی خیلی ممنونت میشم

**Comment by Eslender73** [comment]
> > > > بنظرم از سرتیفیتیکیت کلادفلر استفاده کن بعد تست کن طبق اموزش
> > > 
> > > 
> > > بله خیلی دوست دارم از کلود استفاده کنم ولی چون دسترسی به سیستم ندارم و با گوشی هستم بعد از کپی و توی nano سرتیفیکیت ها درهم و برهم میشند مجبور شدم از این روش استفاده کنم
> > 
> > 
> > منم با گوشی درست کردم فکر نکنم مشکلی پیش بیاره یبار دیگه امتحان کن
> 
> و دستوراتی که زدی رو هم میدی خیلی ممنونت میشم

من سرویس ران کردم یکم باید بلد باشی

**Comment by mohamad15516** [comment]
> > > > > بنظرم از سرتیفیتیکیت کلادفلر استفاده کن بعد تست کن طبق اموزش
> > > > 
> > > > 
> > > > بله خیلی دوست دارم از کلود استفاده کنم ولی چون دسترسی به سیستم ندارم و با گوشی هستم بعد از کپی و توی nano سرتیفیکیت ها درهم و برهم میشند مجبور شدم از این روش استفاده کنم
> > > 
> > > 
> > > منم با گوشی درست کردم فکر نکنم مشکلی پیش بیاره یبار دیگه امتحان کن
> > 
> > و دستوراتی که زدی رو هم میدی خیلی ممنونت میشم
> 
> من سرویس ران کردم یکم باید بلد باشی

اره اوکیه بده بلدم سرویس ران کنم فقط مشخصاتت رو تغییر بده که شناسایی نشه دامنت دمت گرم

**Comment by Eslender73** [comment]
ساخت سرویس در هر دو طرف با دستور
sudo nano /etc/systemd/system/cdn.service


طرف خارج اینو داخلش بزار

[Unit]
Description=my tunnel service

[Service]
Type=idle
User=root
WorkingDirectory=/root
ExecStart=/root/RTCF --kharej --auto:off --domain:cdn.domain.com --iran-port:443 --toip:127.0.0.1 --toport:multiport --password:12345
Restart=always

[Install]
WantedBy=multi-user.target


تو سرور ایران این متنو بزن

[Unit]
Description=my tunnel service

[Service]
Type=idle
User=root
WorkingDirectory=/root
ExecStart=/root/RTCF  --iran --auto:off --cert:/root/cert.cert --pkey:/root/key.key  --domain: cdn.domain.com  --lport:23-65535 --password:12345
Restart=always

[Install]
WantedBy=multi-user.target



ذخیر کن بعد تو هر سرور این دستور رو بزن

systemctl daemon-reload
systemctl start cdn



برای ذخیر سرت هم اموزشش هست با نانو cert و key رو تو root بساز

**Comment by radkesvat** [comment]
مشکلتون پورت کانفیگ توی سرور خارج هست

توی دستور خارج
 --toport:443

و توی سرور ایران گفتی به یه بازه پورت گوش بده

الان طبق این دستورات کاربر به هر پورتی داخل سرور ایران وصل بشه اخرش وصل میشه به ۴۴۳ خارج و کانفگیی هم از قرارمعلوم روی اون پورت نیست که کاربر بهش وصل بشه

**Comment by mohamad15516** [comment]
> مشکلتون پورت کانفیگ توی سرور خارج هست
> 
> توی دستور خارج
>  --toport:443
> 
> و توی سرور ایران گفتی به یه بازه پورت گوش بده
> 
> الان طبق این دستورات کاربر به هر پورتی داخل سرور ایران وصل بشه اخرش وصل میشه به ۴۴۳ خارج و کانفگیی هم از قرارمعلوم روی اون پورت نیست که کاربر بهش وصل بشه

اقا عالی دمتون گرم با ساختن یه کاربر توی پنل ایکس ری روی پورت ۴۴۳ مشکلم حل شد همه کارا رو درست رفته بودم با تشکر ازشما سرعتش خیلی خوبه عالیه عالی ❤️❤️❤️ تا ببینم توی این فیلترینگ شدید دامنه چند روز دوام میاره 😅
