### ISSUE TITLE
خدا قوت

### ISSUE THREAD

**Issue by sajadshadmn** [radkesvat/RTCF#6]
درود مهندس
در حال حاضر فقط تانل معکوس شما جواب میده که اون هم روی اینستا مشکلات زیادی داره
همه چشم و امیدمون به شماست
چشم انتظار پابلیک کردن این پروژه هستیم
ممنون

**Comment by MahdiMadhani** [comment]
مهندس همه منتظریم

**Comment by radkesvat** [comment]
تشکر؛ تمام تلاشم همینه که زود تر اماده بشه

**Comment by ZarinNegah** [comment]
> درود مهندس در حال حاضر فقط تانل معکوس شما جواب میده که اون هم روی اینستا مشکلات زیادی داره همه چشم و امیدمون به شماست چشم انتظار پابلیک کردن این پروژه هستیم ممنون

سلام
سرور خارج کشورتون کجاس
تانل معکوس با هتزنر که مشکل داره و جواب نمیده چند وقته

**Comment by sajadshadmn** [comment]
> > درود مهندس در حال حاضر فقط تانل معکوس شما جواب میده که اون هم روی اینستا مشکلات زیادی داره همه چشم و امیدمون به شماست چشم انتظار پابلیک کردن این پروژه هستیم ممنون
> 
> سلام سرور خارج کشورتون کجاس تانل معکوس با هتزنر که مشکل داره و جواب نمیده چند وقته

سلام
هتزنر دارم
اما عمده مصرفم از هاستیکو هست 
بصورت دایرکت بدون مشکل کار میکنن اما با ریورس خیر
