### ISSUE TITLE
هتزنر و کلودفلر

### ISSUE THREAD

**Issue by ZarinNegah** [radkesvat/RTCF#7]
سلام
عرض خسته نباشید خدمت شما مهندس جان
خوشحالیم که بزودی منتشر میکنید
تست هایی که داشتین با سرورهای هتزنر و فعال کردن پروکسی کلوفلر اوکی بودن و مشکلات اخیر که دیتاسنتر ها ایجاد کردن با موفقیت مقابله کردید؟
تشکر

**Comment by radkesvat** [comment]
بله تست کردم اوکی بود

**Comment by ZarinNegah** [comment]
> بله تست کردم اوکی بود

سلام
خسته نباشید واقعا
دستتون درد نکنه
لطفا گذشته علاوه بر amd برای arm هم قراردهید

**Comment by ZarinNegah** [comment]
سلام
وقت بخیر
مهندس جان من الان اجرا کردم،همه چی به نظر خوبه
فقط موردی که هست،تنظیماتی برای کلودفلر قرارندادین
کاری نیاز نیست ما بکنیم
الان ارتباط سرور ایران با خارج به آی پی ها کلوفلر هستش؟
دیگه فیلتر بودن آی پی خارجمون اهمیتی نداره؟

**Comment by ZarinNegah** [comment]
> سلام وقت بخیر مهندس جان من الان اجرا کردم،همه چی به نظر خوبه فقط موردی که هست،تنظیماتی برای کلودفلر قرارندادین کاری نیاز نیست ما بکنیم الان ارتباط سرور ایران با خارج به آی پی ها کلوفلر هستش؟ دیگه فیلتر بودن آی پی خارجمون اهمیتی نداره؟
سلام
بی زحمت این کامنت هم بررسی میکنید
