### ISSUE TITLE
مشکل TLS

### ISSUE THREAD

**Issue by ali90500** [radkesvat/RTCF#70]
در سرور ایران با ارور

asyncfutures.nim(674)    cb
Error: unhandled exception: Asynchronous task [run() at right.nim:98] finished with an exception "TLSStreamProtocolError"!
Message: Invalid PEM encoding
Stack trace: tlsstream.nim(143)       raiseTLSStreamProtocolError
right.nim(105)           run
dynamic_scope.nim(90)    run
 [FutureDefect]

مواجه میشم فک کنم مشکل از TLS سرور باشه

**Comment by engAmirEng** [comment]
منم این مشکل رو دارم، باید چیکار کرد؟

**Comment by engAmirEng** [comment]
برای من مشکلش این بود که وقتی با vim کپی میکردم مشکل داشت ولی وقتی با nano کپی میکنم درسته😀
