### ISSUE TITLE
Issue with NAT

### ISSUE THREAD

**Issue by msanaii** [radkesvat/RTCF#8]
I tried using the app inside my datacenter, and since I use private IPs on my servers and use NAT, I got the following error:

![image](https://github.com/radkesvat/RTCF/assets/28187426/2dabce95-e375-4243-a529-3833213c600a)

It would be nice if you could add support for such scenario.

Thanks

**Comment by radkesvat** [comment]
ill investigate

**Comment by radkesvat** [comment]
have you checkd your dns settings?

try this command and see if that solves the problem or not

```sh 
echo nameserver 8.8.8.8 | sudo tee /etc/resolv.conf

```

**Comment by msanaii** [comment]
I did try changing the DNS server anyway, but that's not the issue.

What happens is that RTCF wants to determine the server public IP and it fails.

**Comment by radkesvat** [comment]
oh i see, it cant detect your server ip , resolved to a private ip;

ill provide that option to set this by hand in next version

**Comment by moandes** [comment]
دوتا ایرانی سسخل رو تو این ایشو مشاهده میکنیم که درحال زور زدن واسه انگلیسی حرف زدنن :)) فارسی صحبت کنین :)))

**Comment by radkesvat** [comment]
--self-ip is now available
