### ISSUE TITLE
توی نسخه مولتی ترد، تعداد ترد ها روی یک میمونن، چراااااااااااا؟ چرا یه سوییچ نذاشتید که خودم بگم چند تا ترد میخوام؟؟؟؟؟؟؟؟؟؟؟؟؟؟

### ISSUE THREAD

**Issue by engAmirEng** [radkesvat/RTCF#94]
توی نسخه مولتی ترد، تعداد ترد ها روی یک میمونن، چراااااااااااا؟ چرا یه سوییچ نذاشتید که خودم بگم چند تا ترد میخوام؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟

**Comment by Ferixy** [comment]
> توی نسخه مولتی ترد، تعداد ترد ها روی یک میمونن، چراااااااااااا؟ چرا یه سوییچ نذاشتید که خودم بگم چند تا ترد میخوام؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟

این پروژه دیگه آپدیت نمیشه و استفاده ازش پیشنهاد نمیشه. در همون حالت بتا توسعه این تانل قطع شد که به تانل جدید رسیدگی بشه.

**Comment by engAmirEng** [comment]
نه من میخوام ببینم وقتی سختته که با Nim مولتی ترد بنویسی براچی میای سخت ترش میکنی و خودت میای تشخیص میدی کی ترد اضافه بشه و کی کم بشه؟

**Comment by Ferixy** [comment]
> نه من میخوام ببینم وقتی سختته که با Nim مولتی ترد بنویسی براچی میای سخت ترش میکنی و خودت میای تشخیص میدی کی ترد اضافه بشه و کی کم بشه؟

همانطور که بهتون گفتم این پروژه همون اول کاری از برنامه توسعه خارج شد تا روی یک هسته پیشرفته و customizable نوشته شده با زبان C وقت گذاشته بشه که الان داره مراحل بتا رو رد میکنه ، برای همین به این پروژه وقت نشد خیلی قابلیت ها اضافه بشن. این پروژه دیگه آپدیت نمیشه و  استفاده ازش هم پیشنهاد نمیشه.

این پروژه ها بعنوان hobby و بدون پشتوانه/کمک مالی توسعه پیدا میکنن و قطعا جاهایی کم و کاستی ممکنه دیده بشه.
اگر شما فکر میکنید توانایی نوشتن تانل بهتری رو دارید لطف بفرمایید انجام بدید و انقدر تیکت نزنید بهمون که آخرش هم بخواید passive aggressive رفتار کنید.

**Comment by Ferixy** [comment]
> نه من میخوام ببینم وقتی سختته که با Nim مولتی ترد بنویسی براچی میای سخت ترش میکنی و خودت میای تشخیص میدی کی ترد اضافه بشه و کی کم بشه؟

همانطور که بهتون گفتم این پروژه همون اول کاری از برنامه توسعه خارج شد تا روی یک هسته پیشرفته و customizable نوشته شده با زبان C وقت گذاشته بشه که الان داره مراحل بتا رو رد میکنه ، برای همین به این پروژه وقت نشد خیلی قابلیت ها اضافه بشن. این پروژه دیگه آپدیت نمیشه و  استفاده ازش هم پیشنهاد نمیشه.

این پروژه ها بعنوان hobby و بدون پشتوانه/کمک مالی توسعه پیدا میکنن و قطعا جاهایی کم و کاستی ممکنه دیده بشه.
اگر شما فکر میکنید توانایی نوشتن تانل بهتری رو دارید لطف بفرمایید انجام بدید و انقدر تیکت نزنید بهمون که آخرش هم بخواید passive aggressive رفتار کنید.
